Fix #8, solve an issue created by errexit when a binary is missing. Switch over to using -z vs $?

diff --git a/imgopt b/imgopt
--- a/imgopt
+++ b/imgopt
@@ -57,9 +57,10 @@ EOF
 check_bin() {
   # $1 is the binary
   # $2 is the text to print if missing
-  which "${1}" &> /dev/null
-  if [[ "${?}" -ne "0" ]]
+  binary_path="`which "${1}" 2> /dev/null || true`"
+  if [[ -z "${binary_path}" ]]
   then
+    echo "Binary ${1} is missing!"
     echo -e "${2}"
     exit 1
   fi
